from __future__ import annotations

import hashlib
import asyncio
import json
from datetime import UTC, date, datetime
from typing import Any, Callable

from pydantic import BaseModel, Field

from quantlab.config import Settings
from quantlab.domain import AnalysisContextPack, AssetType, MarketQuote
from quantlab.domain.strategy_evidence import AblationVariant, VariantPrediction
from quantlab.domain.data_governance import DataTrustLevel
from quantlab.learning import LearningRepository
from quantlab.learning.trainer import predict_active_model, predict_registered_model
from quantlab.market import QuoteService, ResearchBarService, TradingCalendarService
from quantlab.llm import await_with_provider_close, build_provider
from quantlab.llm.governance import GovernedLLMProvider, budget_from_settings
from quantlab.persistence.evidence import EvidenceRepository
from quantlab.persistence.round5 import Round5Repository
from quantlab.persistence.strategy_evidence import StrategyEvidenceRepository
from quantlab.workflows.context import build_analysis_context_pack
from quantlab.workflows.llm_committee import run_context_committee
from quantlab.workflows.point_in_time import (
    ROUND3_PROTOCOL_VERSION,
    protocol_hash,
    register_round3_protocol,
)


FORWARD_GOVERNANCE_VERSION = "round5-independent-ablation-v2"
FORWARD_PROMPT_VERSION = "forward-raw-single-prompt-v1"
FORWARD_SCHEMA_VERSION = "forward-ablation-v4"


class RawForwardForecast(BaseModel):
    up_probability: float = Field(ge=0, le=1)
    flat_probability: float = Field(ge=0, le=1)
    down_probability: float = Field(ge=0, le=1)
    action: str
    confidence: float = Field(ge=0, le=1)


def create_round3_forward_cohort(
    settings: Settings,
    *,
    frozen_at: datetime | None = None,
) -> dict[str, Any]:
    if frozen_at is not None:
        raise ValueError("forward cohort frozen_at is generated by the server")
    protocol = register_round3_protocol(settings)
    server_frozen_at = datetime.now(UTC)
    governed_hash = hashlib.sha256(
        f"{protocol['protocol_hash']}:{FORWARD_GOVERNANCE_VERSION}".encode("utf-8")
    ).hexdigest()
    return StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    ).create_forward_cohort(
        protocol_version=f"{ROUND3_PROTOCOL_VERSION}+{FORWARD_GOVERNANCE_VERSION}",
        protocol_hash=governed_hash,
        frozen_at=server_frozen_at,
        minimum_matured_samples=30,
        payload={
            "horizons": [5, 20],
            "historical_backfill_allowed": False,
            "protocol_hash_recalculated": protocol_hash(),
            "governance_version": FORWARD_GOVERNANCE_VERSION,
            "server_clock": "UTC",
        },
    )


def freeze_forward_ablation_sample(
    settings: Settings,
    *,
    cohort_id: str,
    symbol: str,
    horizon_days: int,
    account_id: str | None = None,
    quote_service: QuoteService | None = None,
    context_pack: AnalysisContextPack | dict[str, Any] | None = None,
    committee_runner: Callable[..., dict[str, Any]] | None = None,
    raw_llm_runner: Callable[..., dict[str, Any]] | None = None,
    registration_origin: str = "internal",
    formal: bool = False,
    minimum_trust_level: DataTrustLevel | str = DataTrustLevel.SERVER_OBSERVED,
    as_of: date | None = None,
    frozen_role_policy: dict[str, Any] | None = None,
    frozen_statistical_model_id: str | None = None,
    use_active_statistical_model: bool = True,
    variant_policy: dict[str, Any] | None = None,
    sample_key_context_fingerprint: str | None = None,
) -> list[dict[str, Any]]:
    if horizon_days not in {5, 20}:
        raise ValueError("forward ablation horizon must be 5 or 20 days")
    service = quote_service or QuoteService.from_settings(settings)
    asset_type = _asset_type(settings, symbol)
    quote = service.get(
        symbol,
        asset_type=asset_type,
        as_of=as_of,
        require_authoritative=True,
        minimum_trust=minimum_trust_level,
    )
    if formal and (as_of is None or quote.as_of != as_of):
        raise ValueError("formal forward registration requires the exact signal-day quote")
    if context_pack is None:
        existing = EvidenceRepository(
            settings.resolve(settings.get("system.database_path"))
        ).latest_context(symbol, as_of=quote.as_of.isoformat())
        if existing and date.fromisoformat(str(existing.get("as_of"))[:10]) != quote.as_of:
            existing = None
        context_payload = existing or build_analysis_context_pack(
            settings,
            symbol=symbol,
            as_of=quote.as_of,
            asset_type=asset_type.value,
            market_quote=quote,
            account_id=account_id,
            include_events=True,
            save=True,
        )
        pack = AnalysisContextPack.model_validate(context_payload)
    else:
        pack = (
            context_pack
            if isinstance(context_pack, AnalysisContextPack)
            else AnalysisContextPack.model_validate(context_pack)
        )
    if pack.symbol != symbol or pack.as_of > quote.as_of:
        raise ValueError("forward context does not match the authoritative start quote")
    if formal and pack.as_of != quote.as_of:
        raise ValueError("formal forward context must be frozen for the exact signal day")
    deterministic_max_weight = float(settings.get("risk.max_single_position", 0.15))
    runner = committee_runner or run_context_committee
    resolved_role_policy = _resolve_frozen_role_policy(frozen_role_policy, pack)
    try:
        committee = runner(
            settings,
            pack=pack,
            deterministic_max_weight=deterministic_max_weight,
            idempotency_key=(
                f"forward:{cohort_id}:{symbol}:{quote.as_of.isoformat()}:{horizon_days}"
            ),
            role_policy_override=resolved_role_policy,
        )
    except Exception as exc:
        committee = {
            "action": "review_required",
            "confidence": 0.0,
            "suggested_weight_max": 0.0,
            "degraded_roles": ["committee"],
            "failure_type": type(exc).__name__,
        }
    raw_llm = (raw_llm_runner or run_raw_forward_llm)(
        settings,
        pack=pack,
        horizon_days=horizon_days,
        idempotency_key=(
            f"raw-forward:{cohort_id}:{symbol}:{quote.as_of.isoformat()}:{horizon_days}"
        ),
    )
    predictions = _execute_variants(
        settings,
        pack=pack,
        committee=committee,
        horizon_days=horizon_days,
        deterministic_max_weight=deterministic_max_weight,
        raw_llm=raw_llm,
        frozen_statistical_model_id=frozen_statistical_model_id,
        use_active_statistical_model=use_active_statistical_model,
        variant_policy=variant_policy,
    )
    due_at = TradingCalendarService.from_settings(settings).due_at(
        quote.as_of,
        horizon_days,
        formal=formal,
        minimum_trust=minimum_trust_level,
    )
    sample_key = _sample_key(
        cohort_id=cohort_id,
        symbol=symbol,
        account_id=account_id,
        as_of=quote.as_of.isoformat(),
        horizon_days=horizon_days,
        context_fingerprint=sample_key_context_fingerprint or pack.fingerprint,
    )
    return StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    ).register_forward_sample(
        cohort_id=cohort_id,
        sample_key=sample_key,
        symbol=symbol,
        as_of=quote.as_of,
        due_at=due_at,
        horizon_days=horizon_days,
        predictions=predictions,
        context_fingerprint=pack.fingerprint,
        start_price=quote.raw_price,
        quote_source=quote.source,
        quote_provider=quote.provider or quote.source,
        quote_version=quote.source_version,
        quote_fingerprint=quote.quote_fingerprint,
        strategy_version=str(settings.get("strategies.a_share_v4.protocol_version", "unknown")),
        prompt_version=FORWARD_PROMPT_VERSION,
        governance_version=FORWARD_GOVERNANCE_VERSION,
        account_id=account_id,
        registration_origin=registration_origin,
    )


def run_raw_forward_llm(
    settings: Settings,
    *,
    pack: AnalysisContextPack,
    horizon_days: int,
    idempotency_key: str,
) -> dict[str, Any]:
    provider = build_provider(settings.values.get("llm", {}))
    governed = GovernedLLMProvider(
        provider,
        EvidenceRepository(settings.resolve(settings.get("system.database_path"))),
        context_id=pack.context_id,
        context_fingerprint=pack.fingerprint,
        task_id=idempotency_key,
        budget=budget_from_settings(settings.values.get("llm", {})),
        prompt_version=FORWARD_PROMPT_VERSION,
        schema_version=FORWARD_SCHEMA_VERSION,
        governance_version="raw-llm-no-role-governance",
    )
    system = (
        "You are one frozen raw forecasting model. Do not call tools, roles, committees, "
        "quantitative models or governance weights. Use only the supplied compact evidence."
    )
    prompt = json.dumps(
        {
            "horizon_days": horizon_days,
            "context": pack.llm_payload(),
            "required": "probabilities and one action",
        },
        ensure_ascii=False,
        sort_keys=True,
    )
    try:
        result = asyncio.run(
            await_with_provider_close(
                governed,
                governed.structured(system, prompt, RawForwardForecast),
            )
        )
    except Exception as exc:
        return {
            "probabilities": {"up": 1 / 3, "flat": 1 / 3, "down": 1 / 3},
            "action": "observe",
            "confidence": 0.0,
            "complete": False,
            "failure_type": type(exc).__name__,
            "provider": getattr(provider, "provider_name", "unknown"),
            "model": getattr(provider, "model", "unknown"),
        }
    actual_provider = str(
        getattr(result, "_llm_provider", getattr(provider, "provider_name", "unknown"))
    )
    actual_model = str(
        getattr(result, "_llm_model", getattr(provider, "model", "unknown"))
    )
    production_provider = (
        actual_provider.lower() not in {"mock", "fallback", "unknown"}
        and _provider_runtime_is_production(provider)
    )
    if not production_provider:
        return {
            "probabilities": {"up": 1 / 3, "flat": 1 / 3, "down": 1 / 3},
            "action": "observe",
            "confidence": 0.0,
            "complete": False,
            "failure_type": "non_production_llm_provider",
            "provider": actual_provider,
            "model": actual_model,
        }
    return {
        "probabilities": _normalize(
            {
                "up": result.up_probability,
                "flat": result.flat_probability,
                "down": result.down_probability,
            }
        ),
        "action": result.action,
        "confidence": result.confidence,
        "complete": True,
        "provider": actual_provider,
        "model": actual_model,
    }


def settle_forward_ablation_sample(
    settings: Settings,
    **kwargs: Any,
) -> list[dict[str, Any]]:
    """Internal-only immutable settlement primitive used by the Worker."""
    return StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    ).settle_forward_sample(**kwargs)


def forward_ablation_scorecard(
    settings: Settings,
    *,
    cohort_id: str,
    horizon_days: int,
    registration_origin: str | None = None,
) -> dict[str, Any]:
    return StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    ).forward_scorecard(
        cohort_id=cohort_id,
        horizon_days=horizon_days,
        registration_origin=registration_origin,
    )


def forward_account_scorecard(
    settings: Settings,
    *,
    cohort_id: str,
    account_id: str,
) -> dict[str, Any]:
    repository = StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    )
    return {
        "cohort_id": cohort_id,
        "account_id": account_id,
        "horizons": {
            str(horizon): repository.forward_scorecard(
                cohort_id=cohort_id,
                horizon_days=horizon,
                account_id=account_id,
            )
            for horizon in (5, 20)
        },
        "claim_boundary": (
            "Only server-registered, server-settled forward samples linked to this account "
            "are included; research replays and test quotes are excluded."
        ),
    }


def settle_due_forward_sample(
    settings: Settings,
    sample: dict[str, Any],
    *,
    quote_service: QuoteService | None = None,
    bar_service: ResearchBarService | None = None,
) -> dict[str, Any]:
    repository = StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    )
    due_date = datetime.fromisoformat(sample["due_at"]).date()
    try:
        if sample.get("registration_origin") == "automatic_primary":
            experiment = Round5Repository(
                settings.resolve(settings.get("system.database_path"))
            ).experiment_for_cohort(sample["cohort_id"])
            if experiment is None:
                raise ValueError("primary experiment protocol is unavailable")
            minimum_trust = experiment["minimum_trust_level"]
            observation = (bar_service or ResearchBarService.from_settings(settings)).get(
                sample["symbol"],
                as_of=due_date,
                minimum_trust=minimum_trust,
                exact=True,
            )
            quote = MarketQuote(
                symbol=sample["symbol"],
                asset_type=_asset_type(settings, sample["symbol"]),
                raw_price=observation.bar.close,
                as_of=observation.bar.date,
                available_at=observation.bar.available_at,
                source=observation.source,
                provider=observation.provider,
                source_version=observation.source_version,
                trust_level=observation.trust_level,
                license_status=observation.license_status,
                endpoint=observation.endpoint,
                raw_payload_fingerprint=observation.raw_fingerprint,
                quote_fingerprint=observation.payload_fingerprint,
                session_status="closed",
            )
        else:
            quote = (quote_service or QuoteService.from_settings(settings)).get(
                sample["symbol"],
                asset_type=_asset_type(settings, sample["symbol"]),
                as_of=due_date,
                require_authoritative=True,
            )
    except Exception as exc:
        attempt = repository.record_forward_settlement_attempt(
            cohort_id=sample["cohort_id"],
            sample_key=sample["sample_key"],
            horizon_days=int(sample["horizon_days"]),
            status="pending",
            reason=f"authoritative_quote_unavailable:{type(exc).__name__}",
        )
        return {"settled": False, **attempt}
    if quote.as_of < due_date:
        attempt = repository.record_forward_settlement_attempt(
            cohort_id=sample["cohort_id"],
            sample_key=sample["sample_key"],
            horizon_days=int(sample["horizon_days"]),
            status="pending",
            reason="authoritative_quote_has_not_reached_due_trading_day",
            quote_fingerprint=quote.quote_fingerprint,
        )
        return {"settled": False, **attempt}
    server_observed_at = datetime.now(UTC)
    quote_available_at = quote.available_at or server_observed_at
    if quote_available_at > server_observed_at:
        attempt = repository.record_forward_settlement_attempt(
            cohort_id=sample["cohort_id"],
            sample_key=sample["sample_key"],
            horizon_days=int(sample["horizon_days"]),
            status="pending",
            reason="authoritative_quote_available_at_is_in_the_future",
            quote_fingerprint=quote.quote_fingerprint,
        )
        return {"settled": False, **attempt}
    observed_at = server_observed_at
    start_price = float(sample["start_price"])
    realized_return_pct = (quote.raw_price / start_price - 1.0) * 100.0
    transaction_cost_pct = _variant_costs(settings, sample)
    outcomes = repository.settle_forward_sample(
        cohort_id=sample["cohort_id"],
        sample_key=sample["sample_key"],
        horizon_days=int(sample["horizon_days"]),
        realized_return_pct=realized_return_pct,
        outcome_source=(
            f"{quote.provider or quote.source}:{quote.source_version}:"
            f"{quote.quote_fingerprint}"
        ),
        observed_at=observed_at,
        flat_threshold_pct=float(settings.get("calibration.flat_threshold_pct", 1.0)),
        turnover_by_variant={key: value["turnover"] for key, value in transaction_cost_pct.items()},
        drawdown_by_variant={
            key: min(0.0, realized_return_pct * value["target_weight"] - value["cost_pct"])
            for key, value in transaction_cost_pct.items()
        },
        transaction_cost_pct_by_variant={
            key: value["cost_pct"] for key, value in transaction_cost_pct.items()
        },
        payload={
            "start_price": start_price,
            "end_price": quote.raw_price,
            "quote": quote.model_dump(mode="json"),
            "calculation": "(end_price/start_price-1)*100",
            "minimum_trust_level": (
                minimum_trust
                if sample.get("registration_origin") == "automatic_primary"
                else None
            ),
        },
    )
    repository.record_forward_settlement_attempt(
        cohort_id=sample["cohort_id"],
        sample_key=sample["sample_key"],
        horizon_days=int(sample["horizon_days"]),
        status="settled",
        reason=None,
        quote_fingerprint=quote.quote_fingerprint,
    )
    return {"settled": True, "outcomes": outcomes}


def _execute_variants(
    settings: Settings,
    *,
    pack: AnalysisContextPack,
    committee: dict[str, Any],
    horizon_days: int,
    deterministic_max_weight: float,
    raw_llm: dict[str, Any],
    frozen_statistical_model_id: str | None = None,
    use_active_statistical_model: bool = True,
    variant_policy: dict[str, Any] | None = None,
) -> list[VariantPrediction]:
    policy = {
        "baseline_probabilities": {"up": 0.45, "flat": 0.30, "down": 0.25},
        "baseline_weight": float(
            settings.get("strategies.forward_primary.simple_baseline_weight", 0.05)
        ),
        "entry_score_threshold": 0.20,
        "avoid_score_threshold": -0.20,
        "llm_stat_statistical_weight": 0.50,
        "full_committee_weight": 0.35,
        "full_statistical_weight": 0.25,
        "full_baseline_weight": 0.05,
        "llm_gate_pass_actions": ["buy", "add", "hold"],
        "full_block_actions": ["avoid", "reduce", "review_required"],
        **(variant_policy or {}),
    }
    quant_score = _quant_score(pack)
    quant_probabilities = _probabilities_from_score(quant_score)
    baseline_probabilities = _normalize(policy["baseline_probabilities"])
    baseline_score = _score(baseline_probabilities)
    raw_llm_probabilities = _normalize(raw_llm["probabilities"])
    runtime = committee.get("llm_runtime") or {}
    role_complete = 0.0 if committee.get("degraded_roles") else 1.0
    if runtime and not bool(runtime.get("production_provider_available")):
        role_complete = 0.0
    committee_probabilities = (
        _committee_probabilities(committee)
        if role_complete
        else _probabilities_from_score(0.0)
    )
    model_repository = LearningRepository(
        settings.resolve(settings.get("system.database_path"))
    )
    features = {
        "quant_score": quant_score,
        "context_quality": pack.quality_score,
        "horizon_days": float(horizon_days),
    }
    if use_active_statistical_model:
        statistical = predict_active_model(
            model_repository,
            horizon_days,
            "etf" if pack.asset_type == AssetType.ETF else "stock",
            features,
        )
    elif frozen_statistical_model_id:
        statistical = predict_registered_model(
            model_repository,
            frozen_statistical_model_id,
            features,
        )
    else:
        statistical = None
    if statistical:
        stat_probabilities = {
            "up": float(statistical["up_probability"]),
            "flat": float(statistical["flat_probability"]),
            "down": float(statistical["down_probability"]),
        }
        stat_complete = 1.0 if statistical["governance_status"] == "governed" else 0.0
    else:
        stat_probabilities = {"up": 1 / 3, "flat": 1 / 3, "down": 1 / 3}
        stat_complete = 0.0
    fusion_probabilities = _blend(
        raw_llm_probabilities,
        stat_probabilities,
        float(policy["llm_stat_statistical_weight"]),
    )
    full_probabilities = _blend(
        _blend(
            quant_probabilities,
            committee_probabilities,
            float(policy["full_committee_weight"]),
        ),
        stat_probabilities,
        float(policy["full_statistical_weight"]) if stat_complete else 0.0,
    )
    full_probabilities = _blend(
        full_probabilities,
        baseline_probabilities,
        float(policy["full_baseline_weight"]),
    )
    llm_action = str(committee.get("action") or "review_required")
    llm_weight = min(
        deterministic_max_weight,
        max(0.0, float(committee.get("suggested_weight_max") or 0.0)),
    )
    entry_threshold = float(policy["entry_score_threshold"])
    quant_weight = deterministic_max_weight if quant_score >= entry_threshold else 0.0
    gated_weight = (
        quant_weight if llm_action in set(policy["llm_gate_pass_actions"]) else 0.0
    )
    full_weight = min(
        deterministic_max_weight,
        max(0.0, (quant_weight + llm_weight) / 2),
    )
    raw_complete = 1.0 if raw_llm.get("complete") else 0.0
    baseline_weight = min(
        deterministic_max_weight,
        float(policy["baseline_weight"]),
    )
    common = {
        "data_completeness": pack.quality_score,
        "payload": {
            "schema_version": FORWARD_SCHEMA_VERSION,
            "governance_version": FORWARD_GOVERNANCE_VERSION,
            "context_id": pack.context_id,
            "statistical_model_id": statistical.get("model_id") if statistical else None,
            "variant_policy": policy,
            "raw_llm_provider": raw_llm.get("provider"),
            "raw_llm_model": raw_llm.get("model"),
            "committee_llm_runtime": runtime,
        },
    }
    return [
        _prediction(AblationVariant.SIMPLE_BASELINE, baseline_probabilities, baseline_score, baseline_weight, 1.0, common, policy),
        _prediction(AblationVariant.QUANT_ONLY, quant_probabilities, quant_score, quant_weight, 1.0, common, policy),
        _prediction(AblationVariant.RAW_LLM, raw_llm_probabilities, _score(raw_llm_probabilities), deterministic_max_weight if raw_complete and _score(raw_llm_probabilities) >= entry_threshold else 0.0, raw_complete, common, policy),
        _prediction(AblationVariant.STATISTICAL_MODEL, stat_probabilities, _score(stat_probabilities), deterministic_max_weight if stat_complete and _score(stat_probabilities) >= entry_threshold else 0.0, stat_complete, common, policy),
        _prediction(AblationVariant.LLM_STAT_FUSION, fusion_probabilities, _score(fusion_probabilities), deterministic_max_weight if raw_complete and stat_complete and _score(fusion_probabilities) >= entry_threshold else 0.0, min(raw_complete, stat_complete), common, policy),
        _prediction(AblationVariant.LLM_TRADE_GATE, quant_probabilities, quant_score, gated_weight, role_complete, common, policy),
        _prediction(AblationVariant.FULL_SYSTEM, full_probabilities, _score(full_probabilities), full_weight if llm_action not in set(policy["full_block_actions"]) else 0.0, min(role_complete, 1.0 if pack.quality_score >= 0.7 else 0.5), common, policy),
    ]


def _prediction(
    variant: AblationVariant,
    probabilities: dict[str, float],
    score: float,
    target_weight: float,
    role_completeness: float,
    common: dict[str, Any],
    policy: dict[str, Any] | None = None,
) -> VariantPrediction:
    avoid_threshold = float((policy or {}).get("avoid_score_threshold", -0.20))
    action = (
        "buy"
        if target_weight > 0 and score > 0
        else "avoid"
        if score < avoid_threshold
        else "observe"
    )
    return VariantPrediction(
        variant=variant,
        probabilities=probabilities,
        action=action,
        target_weight=target_weight,
        actually_triggered=target_weight > 0,
        data_completeness=float(common["data_completeness"]),
        role_completeness=max(0.0, min(1.0, role_completeness)),
        payload={**common["payload"], "signal_score": score},
    )


def _quant_score(pack: AnalysisContextPack) -> float:
    values: list[float] = []
    for block in pack.blocks:
        if block.domain.value not in {"technical", "strategy", "market"}:
            continue
        values.extend(_bounded_numeric_values(block.payload))
    if not values:
        return 0.0
    normalized = sum(max(-20.0, min(20.0, value)) for value in values[:40]) / max(1, len(values[:40]))
    return max(-1.0, min(1.0, normalized / 10.0))


def _bounded_numeric_values(value: Any) -> list[float]:
    output: list[float] = []
    if isinstance(value, dict):
        for key, item in value.items():
            if any(token in key.lower() for token in ("return", "momentum", "score", "trend")):
                if isinstance(item, (int, float)) and not isinstance(item, bool):
                    output.append(float(item))
                else:
                    output.extend(_bounded_numeric_values(item))
    elif isinstance(value, list):
        for item in value[-20:]:
            output.extend(_bounded_numeric_values(item))
    return output


def _probabilities_from_score(score: float) -> dict[str, float]:
    bounded = max(-1.0, min(1.0, score))
    flat = 0.20 + 0.20 * (1.0 - abs(bounded))
    directional = 1.0 - flat
    up = directional * (0.5 + 0.5 * bounded)
    down = directional - up
    return _normalize({"up": up, "flat": flat, "down": down})


def _committee_probabilities(committee: dict[str, Any]) -> dict[str, float]:
    confidence = max(0.0, min(1.0, float(committee.get("confidence") or 0.0)))
    action = str(committee.get("action") or "review_required")
    score = confidence if action in {"buy", "add", "hold"} else -confidence if action in {"reduce", "avoid"} else 0.0
    return _probabilities_from_score(score)


def _blend(first: dict[str, float], second: dict[str, float], second_weight: float) -> dict[str, float]:
    weight = max(0.0, min(1.0, second_weight))
    return _normalize({key: first[key] * (1 - weight) + second[key] * weight for key in ("up", "flat", "down")})


def _resolve_frozen_role_policy(
    frozen: dict[str, Any] | None,
    pack: AnalysisContextPack,
) -> dict[str, Any] | None:
    if not frozen:
        return None
    if "roles" in frozen and "governance_version" in frozen:
        return frozen
    regime = str(pack.deterministic_summary.get("market_regime") or "default")
    return frozen.get(regime) or frozen.get("default")


def _provider_runtime_is_production(provider: Any) -> bool:
    snapshot = provider.health_snapshot()
    endpoints = snapshot.get("endpoints") or []
    if endpoints:
        return any(
            str(item.get("provider") or "unknown").lower()
            not in {"mock", "fallback", "unknown"}
            for item in endpoints
        )
    return str(snapshot.get("provider") or "unknown").lower() not in {
        "mock",
        "fallback",
        "unknown",
    }


def _normalize(value: dict[str, float]) -> dict[str, float]:
    total = sum(max(0.0, float(item)) for item in value.values()) or 1.0
    normalized = {key: max(0.0, float(value.get(key, 0.0))) / total for key in ("up", "flat", "down")}
    normalized["down"] += 1.0 - sum(normalized.values())
    return normalized


def _score(probabilities: dict[str, float]) -> float:
    return float(probabilities["up"]) - float(probabilities["down"])


def _sample_key(**payload: Any) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def _asset_type(settings: Settings, symbol: str) -> AssetType:
    if symbol in set(settings.get("strategies.etf_rotation.universe", [])):
        return AssetType.ETF
    return AssetType.STOCK


def _variant_costs(settings: Settings, sample: dict[str, Any]) -> dict[str, dict[str, float]]:
    repository = StrategyEvidenceRepository(
        settings.resolve(settings.get("system.database_path"))
    )
    with repository.connect() as db:
        rows = db.execute(
            """
            SELECT variant,target_weight,actually_triggered
            FROM forward_ablation_predictions
            WHERE cohort_id=? AND sample_key=? AND horizon_days=?
            """,
            (sample["cohort_id"], sample["sample_key"], int(sample["horizon_days"])),
        ).fetchall()
    round_trip_rate = (
        float(settings.get("costs.stock.commission_rate", 0.00025)) * 2
        + float(settings.get("costs.stock.stamp_duty_rate", 0.0005))
        + float(settings.get("costs.stock.transfer_fee_rate", 0.00001)) * 2
        + float(settings.get("costs.stock.slippage_bps", 10.0)) * 2 / 10_000
    )
    return {
        str(row["variant"]): {
            "target_weight": float(row["target_weight"]),
            "turnover": float(row["target_weight"]) if row["actually_triggered"] else 0.0,
            "cost_pct": float(row["target_weight"]) * round_trip_rate * 100.0,
        }
        for row in rows
    }


__all__ = [
    "create_round3_forward_cohort",
    "forward_ablation_scorecard",
    "forward_account_scorecard",
    "freeze_forward_ablation_sample",
    "run_raw_forward_llm",
    "settle_due_forward_sample",
    "settle_forward_ablation_sample",
]
